spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oranje_main?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: oranje
    password: bXZqOLfh3k
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  session:
    jdbc:
      initialize-schema: always
google:
  recaptcha:
    key:
      site: 6LeDaHUaAAAAAPtUsxhTwt4TXVzF1IN7KSodavV0
      secret: 6LeDaHUaAAAAAKN92JUvpu43pUzA1R_h6Ds3e40g