spring:
  datasource:
    url: jdbc:h2:mem:oranje_main?serverTimezone=UTC&useLegacyDatetimeCode=false
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

