spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oranje_main?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: oranje
    password: bXZqOLfh3k
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  session:
    jdbc:
      initialize-schema: always
google:
  recaptcha:
    site: 6LeDaHUaAAAAAPtUsxhTwt4TXVzF1IN7KSodavV0
    secret: 6LeDaHUaAAAAAKN92JUvpu43pUzA1R_h6Ds3e40g
    # Empty captcha does not count for failure
    max-failures-before-block: 4
    # For how many hours we block the user (IP) from retrying
    hours-to-drop-block: 4
custom:
  login:
    # How many times the user (IP) can fail the login before requiring captcha
    max-attempts-before-captcha: 3
    # For how many hours we require captcha verification from the user (IP)
    hours-to-drop-captcha: 1

